name: Continious integration pipeline

on:
  pull_request:
    types: [opened, reopened]

  workflow_dispatch:

jobs:
  Package-and-test-code:
    env:
      CREDS: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_CICD_DEMO_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout and package code
        uses: actions/checkout@v4

      - name: Prepare test
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Test code
        run: python test.py